    - name: Invoke deployment hook

      uses: distributhor/workflow-webhook@v2

      env:

        webhook_type: 'form-urlencoded'

        webhook_url: ${{ secrets.idk }}


        data: 'weapon=hammer&drink=beer'
