    - name: Invoke deployment hook

      uses: distributhor/workflow-webhook@v2

      env:

        webhook_type: 'form-urlencoded'

        webhook_url: ${{ secrets.WEBHOOK_URL }}

        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}

        data: 'weapon=hammer&drink=beer'
